#server:
#  port: 9090
spring:
  data:
    mongodb:
      host: ds145315.mlab.com
      username: Braidner
      password: Pkjqflvby!
      database: runner
      port: 45315

google:
  client_id: ${GOOGLE_CLIENT_ID:none}
  client_secret: ${GOOGLE_CLIENT_SECRET:none}